#pragma once

#include "NativeGameplayTags.h"

namespace PDGameplayTags
{
	/** Input Tags **/
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Equip_Slot1);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Equip_Slot2);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Equip_Slot3);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Equip_Slot4);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Unequip);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Reload);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_ADS);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_ChangeFireMode);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Throwable_Throw);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_SkillQ);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_SkillE);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Movement_Dash);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Movement_WallJump);

	/** Player Tags **/
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Equip);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Unequip);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Fire);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Reload);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_ADS);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_ChangeFireMode);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Throwable_Throw);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Movement);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Movement_Dash);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Movement_WallJump);

	/** Player State Tags **/
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Firinig);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Equipping);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Unequipping);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Reloading);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Throwing);
	
	/** Event Tags **/
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Weapon_EquipRequest);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Weapon_UnequipRequest);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Weapon_ReloadRequest);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Throwable_ThrowRequest);
	
	/** GameplayCue Tags **/
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Fire);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Throwable_Explosion_Fragment);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Throwable_Explosion_Flame);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Throwable_Explosion_Smoke);
	
	/** SetByCaller Tags **/
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Weapon_Damage);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Weapon_DestructDamage);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Weapon_FireInterval);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Throwable_Fragment_Damage);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Throwable_Flame_Damage);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Weapon_Fire);

	/** Gimmick Tags **/
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gimmick_Interactable_ZipLine);
}